### ISSUE TITLE
Ad astra incompatibility

### ISSUE THREAD

**Issue by Vikthos** [WunderFunct/WFCaveOverhaul#10]
When using Ad Astra and WFCaveOverhaul underground rivers from WFCaveOverhaul generate on planets from Ad Astra.
This ruins the immersion because water shouldn't be on for example the moon.

Possible fix could be restricting the generation to be only in the overworld dimension.
Great mod btw :)

**Comment by WunderFunct** [comment]
Thanks. The code path in question doesn't offer a solid way of confirming which level we're generating terrain in for several reasons. I'll try taking another crack at finding a better way to confirm that it's the overworld being generated but no guarantees. I might have to add a config option to disable rivers as a workaround.

**Comment by WunderFunct** [comment]
The latest 1.3.3 for each version will have this fixed. That'd be 1.3.3.1 onwards for Forge-1.20.1 and 1.3.3 for every other supported version (working on porting code for those). Closing this ticket. Please leave a message if there're still issues and I'll reopen it.

Again, thanks for reporting this issue!
