### ISSUE TITLE
Fabric 1.20.1 Incompatible with Quilt

### ISSUE THREAD

**Issue by moderatetobelowaverage** [WunderFunct/WFCaveOverhaul#2]
Tried using the fabric 1.20.1 release on the latest version of the quilt loader. Threw an error because WFCaves wants fabric loader v0.15.6 and quilt loader only has parity with v0.15.3.

Solution should just be changing the `"fabricloader": ">=0.15.6",` => `"fabricloader": ">=0.15.3",` in `fabric.mod.json`, and `loader_version=0.15.6` => `loader_version=0.15.3` for the `gradle.properties` file, But i wasn't able to test to make sure.

if you used the same loader version for all the fabric releases then its likely this extends to those as well but I haven't checked.

I would have made a PR but without the gradle files I had trouble building and testing the fix.

**Comment by WunderFunct** [comment]
Thanks, I'll look into this.

**Comment by moderatetobelowaverage** [comment]
Looks like this has been updated from the Quilt loader side of things in a public beta. Shouldn't be too long before the release version has parity and this isnt an issue anymore.
