### ISSUE TITLE
Infinity Caves Compat?

### ISSUE THREAD

**Issue by ConqAra** [WunderFunct/WFCaveOverhaul#4]
Unsure if cave overhaul works properly with this mod: [Infinity Caves](https://modrinth.com/datapack/infinity-cave)
"Infinity Cave changes the world height from -64 to -128 and adds a new type of cave generation where it all interconnects into an absurdly giant cave system"
I'm not seeing those special caves connect that way with this mod, but could be a different issue if you've already tested.

**Comment by WunderFunct** [comment]
Noted. I'm working on a series of compat patches. This issue might be fixed in 1.3.3 if you change the config to re-enable default caverns. I'll need to confirm if this bug is still happening when I can.

**Comment by WunderFunct** [comment]
Working on this issue now. 1.3.3 isn't compatible with Infinity Caves. I've diagnosed the problem- infinity caves creates a new overworld under a new name, which is a case my code doesn't currently anticipate. If the fix I'm working on works as expected, 1.3.4 will have a fix for infinity caves.

**Comment by WunderFunct** [comment]
OK, infinity caves should now be working properly in 1.3.3.x :)
