### ISSUE TITLE
Fabric tectonic compat problem

### ISSUE THREAD

**Issue by ThatKatNaps** [WunderFunct/WFCaveOverhaul#5]
mountains and places generated higher up work, but places lower like beach's, stoney shores, plains, and deserts spawn beneath the water

tested on

- 1.20.1

- 1.20.4

only tectonic, cave overhaul, and fabric api are needed to reproduce the issue

**Comment by WunderFunct** [comment]
Thanks. I'm working on a series of compat patches and will check what the behavior is for 1.20.1 fabric tectonic. Please note that 1.20.4 is no longer supported; only 1.20.1, 1.20.6 (some releases are currently pending for this version), and the most recent version of MC.

**Comment by WunderFunct** [comment]
I've reworked how worldgen disabling is done. The new method is quite surgical and uses a whitelist so tectonic's overworld features are retained as well as major tectonic cave features (e.g. lava rivers).
