### ISSUE TITLE
Safe to uninstall?

### ISSUE THREAD

**Issue by Typhonidite** [WunderFunct/WFCaveOverhaul#7]
I'd like to use this in my long-term multiplayer server, but I'd like to know if there'll be any errors or such if removed afterwards. I haven't tested it myself, but will the world work fine (no errors, corruptions, and return to normal cave generation) when the mod is uninstalled?

**Comment by Insane96** [comment]
Can confirm. New chunks generated with vanilla caves.

But still, backups are your friend

**Comment by WunderFunct** [comment]
Thanks! Yes, it should be safe to uninstall. You might see some walls underground where the old worldgen ends and your new worldgen starts, but beyond that, you should be fine.
