### ISSUE TITLE
underground features generating in oceans

### ISSUE THREAD

**Issue by motyI** [WunderFunct/WFCaveOverhaul#8]
What the title says. This includes any features which involve water, such as underground rivers or ponds. The mod can also sometimes generate air pockets inside water, some of which disappear by themselves, but others dont.
![2024-05-28_20 13 25](https://github.com/WunderFunct/WFCaveOverhaul/assets/83429505/17b0782f-1352-4034-ac5d-4c23e4a12c37)
![2024-05-28_20 13 35](https://github.com/WunderFunct/WFCaveOverhaul/assets/83429505/c90ae0aa-e9bf-4384-83cc-6d22f71419e6)
![2024-05-28_20 19 33](https://github.com/WunderFunct/WFCaveOverhaul/assets/83429505/6ff38364-deae-474e-ad24-d52e78d779cf)

**Comment by WunderFunct** [comment]
Oof. That's bad!

But I think I patched this one in my most recent update. Please open a new ticket if you're still having issues. Thanks!
